# Generated by Django 6.0.1 on 2026-01-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='User',
        ),
        migrations.AddField(
            model_name='fund',
            name='donated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='phoneno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
