# Generated by Django 6.0.1 on 2026-02-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_fund_user_fund_donated_at_fund_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='razorpay_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
