# Generated by Django 6.0.1 on 2026-02-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fund_is_paid_fund_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='razorpay_payment_id',
        ),
    ]
