# Generated by Django 6.0.1 on 2026-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_fund_total_raised'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='total_raised',
        ),
        migrations.AddField(
            model_name='fund',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
