# Generated by Django 6.0.1 on 2026-02-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_fund_total_raised_fund_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='total_raised',
            field=models.IntegerField(default=0),
        ),
    ]
