# Generated by Django 6.0.1 on 2026-02-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='campaign_files/'),
        ),
    ]
